const endpoints = [
  {name: '/v2/account', url: '/v2/account', matchSnapshot: true, matchSchema: true},
  {name: '/v2/account/achievements', url: '/v2/account/achievements', matchSnapshot: true, matchSchema: true},
  {name: '/v2/account/bank', url: '/v2/account/bank', matchSnapshot: true, matchSchema: true},
  {name: '/v2/account/dungeons', url: '/v2/account/dungeons', matchSnapshot: true, matchSchema: true},
  {name: '/v2/account/dyes', url: '/v2/account/dyes', matchSnapshot: true, matchSchema: true},
  {name: '/v2/account/finishers', url: '/v2/account/finishers', matchSnapshot: true, matchSchema: true},
  {name: '/v2/account/gliders', url: '/v2/account/gliders', matchSnapshot: true, matchSchema: true},
  {name: '/v2/account/home/cats', url: '/v2/account/home/cats', matchSnapshot: true, matchSchema: true},
  {name: '/v2/account/home/nodes', url: '/v2/account/home/nodes', matchSnapshot: true, matchSchema: true},
  {name: '/v2/account/inventory', url: '/v2/account/inventory', matchSnapshot: true, matchSchema: true},
  {name: '/v2/account/mailcarriers', url: '/v2/account/mailcarriers', matchSnapshot: true, matchSchema: true},
  {name: '/v2/account/masteries', url: '/v2/account/masteries', matchSnapshot: true, matchSchema: true},
  {name: '/v2/account/mastery/points', url: '/v2/account/mastery/points', matchSnapshot: true, matchSchema: true},
  {name: '/v2/account/materials', url: '/v2/account/materials', matchSnapshot: true, matchSchema: true},
  {name: '/v2/account/minis', url: '/v2/account/minis', matchSnapshot: true, matchSchema: true},
  {name: '/v2/account/outfits', url: '/v2/account/outfits', matchSnapshot: true, matchSchema: true},
  {name: '/v2/account/pvp/heroes', url: '/v2/account/pvp/heroes', matchSnapshot: true, matchSchema: true},
  {name: '/v2/account/raids', url: '/v2/account/raids', matchSnapshot: true, matchSchema: true},
  {name: '/v2/account/recipes', url: '/v2/account/recipes', matchSnapshot: true, matchSchema: true},
  {name: '/v2/account/skins', url: '/v2/account/skins', matchSnapshot: true, matchSchema: true},
  {name: '/v2/account/titles', url: '/v2/account/titles', matchSnapshot: true, matchSchema: true},
  {name: '/v2/account/wallet', url: '/v2/account/wallet', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/achievements', url: '/v2/achievements', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/achievements/categories', url: '/v2/achievements/categories', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/achievements/daily', url: '/v2/achievements/daily', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/achievements/daily/tomorrow', url: '/v2/achievements/daily/tomorrow', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/achievements/groups', url: '/v2/achievements/groups', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/backstory/answers', url: '/v2/backstory/answers', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/backstory/questions', url: '/v2/backstory/questions', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/build', url: '/v2/build', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/cats', url: '/v2/cats', matchSnapshot: false, matchSchema: false},
  // {name: '/v2/characters', url: '/v2/characters', matchSnapshot: true, matchSchema: true},
  {name: '/v2/characters/Eff Testing Ele/backstory', url: '/v2/characters/Eff Testing Ele/backstory', matchSnapshot: true, matchSchema: true},
  {name: '/v2/characters/Eff Testing Ele/core', url: '/v2/characters/Eff Testing Ele/core', matchSnapshot: true, matchSchema: true},
  {name: '/v2/characters/Eff Testing Ele/crafting', url: '/v2/characters/Eff Testing Ele/crafting', matchSnapshot: true, matchSchema: true},
  {name: '/v2/characters/Eff Testing Ele/equipment', url: '/v2/characters/Eff Testing Ele/equipment', matchSnapshot: true, matchSchema: true},
  {name: '/v2/characters/Eff Testing Ele/heropoints', url: '/v2/characters/Eff Testing Ele/heropoints', matchSnapshot: true, matchSchema: true},
  {name: '/v2/characters/Eff Testing Ele/inventory', url: '/v2/characters/Eff Testing Ele/inventory', matchSnapshot: true, matchSchema: true},
  {name: '/v2/characters/Eff Testing Ele/recipes', url: '/v2/characters/Eff Testing Ele/recipes', matchSnapshot: true, matchSchema: true},
  {name: '/v2/characters/Eff Testing Ele/sab', url: '/v2/characters/Eff Testing Ele/sab', matchSnapshot: true, matchSchema: true},
  {name: '/v2/characters/Eff Testing Ele/skills', url: '/v2/characters/Eff Testing Ele/skills', matchSnapshot: true, matchSchema: true},
  {name: '/v2/characters/Eff Testing Ele/specializations', url: '/v2/characters/Eff Testing Ele/specializations', matchSnapshot: true, matchSchema: true},
  {name: '/v2/characters/Eff Testing Ele/training', url: '/v2/characters/Eff Testing Ele/training', matchSnapshot: true, matchSchema: true},
  {name: '/v2/colors', url: '/v2/colors', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/commerce/delivery', url: '/v2/commerce/delivery', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/commerce/exchange', url: '/v2/commerce/exchange', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/commerce/listings', url: '/v2/commerce/listings', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/commerce/prices', url: '/v2/commerce/prices', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/commerce/transactions', url: '/v2/commerce/transactions', matchSnapshot: true, matchSchema: true}, TODO
  // {name: '/v2/continents', url: '/v2/continents', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/currencies', url: '/v2/currencies', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/dungeons', url: '/v2/dungeons', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/emblem', url: '/v2/emblem', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/files', url: '/v2/files', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/finishers', url: '/v2/finishers', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/gliders', url: '/v2/gliders', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/guild/:id', url: '/v2/guild/:id', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/guild/:id/log', url: '/v2/guild/:id/log', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/guild/:id/members', url: '/v2/guild/:id/members', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/guild/:id/ranks', url: '/v2/guild/:id/ranks', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/guild/:id/stash', url: '/v2/guild/:id/stash', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/guild/:id/storage', url: '/v2/guild/:id/storage', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/guild/:id/teams', url: '/v2/guild/:id/teams', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/guild/:id/treasury', url: '/v2/guild/:id/treasury', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/guild/:id/upgrades', url: '/v2/guild/:id/upgrades', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/guild/permissions', url: '/v2/guild/permissions', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/guild/search', url: '/v2/guild/search', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/guild/upgrades', url: '/v2/guild/upgrades', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/items', url: '/v2/items', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/itemstats', url: '/v2/itemstats', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/legends', url: '/v2/legends', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/mailcarriers', url: '/v2/mailcarriers', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/maps', url: '/v2/maps', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/masteries', url: '/v2/masteries', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/materials', url: '/v2/materials', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/minis', url: '/v2/minis', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/nodes', url: '/v2/nodes', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/outfits', url: '/v2/outfits', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/pets', url: '/v2/pets', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/professions', url: '/v2/professions', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/pvp', url: '/v2/pvp', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/pvp/amulets', url: '/v2/pvp/amulets', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/pvp/games', url: '/v2/pvp/games', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/pvp/heroes', url: '/v2/pvp/heroes', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/pvp/ranks', url: '/v2/pvp/ranks', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/pvp/seasons', url: '/v2/pvp/seasons', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/pvp/seasons/:id/leaderboards', url: '/v2/pvp/seasons/:id/leaderboards', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/pvp/seasons/:id/leaderboards/:board/:region', url: '/v2/pvp/seasons/:id/leaderboards/:board/:region', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/pvp/standings', url: '/v2/pvp/standings', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/pvp/stats', url: '/v2/pvp/stats', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/quaggans', url: '/v2/quaggans', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/races', url: '/v2/races', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/raids', url: '/v2/raids', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/recipes', url: '/v2/recipes', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/recipes/search', url: '/v2/recipes/search', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/skills', url: '/v2/skills', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/skins', url: '/v2/skins', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/specializations', url: '/v2/specializations', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/stories', url: '/v2/stories', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/stories/seasons', url: '/v2/stories/seasons', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/titles', url: '/v2/titles', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/tokeninfo', url: '/v2/tokeninfo', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/traits', url: '/v2/traits', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/worlds', url: '/v2/worlds', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/wvw/abilities', url: '/v2/wvw/abilities', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/wvw/matches', url: '/v2/wvw/matches', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/wvw/matches/overview', url: '/v2/wvw/matches/overview', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/wvw/matches/scores', url: '/v2/wvw/matches/scores', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/wvw/matches/stats', url: '/v2/wvw/matches/stats', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/wvw/matches/stats/:id/guilds/:guild_id', url: '/v2/wvw/matches/stats/:id/guilds/:guild_id', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/wvw/matches/stats/:id/teams/:team/top/kdr', url: '/v2/wvw/matches/stats/:id/teams/:team/top/kdr', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/wvw/matches/stats/:id/teams/:team/top/kills', url: '/v2/wvw/matches/stats/:id/teams/:team/top/kills', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/wvw/objectives', url: '/v2/wvw/objectives', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/wvw/ranks', url: '/v2/wvw/ranks', matchSnapshot: true, matchSchema: true},
  // {name: '/v2/wvw/upgrades', url: '/v2/wvw/upgrades', matchSnapshot: true, matchSchema: true}
]

module.exports = endpoints
